In [10]:
import numpy as np

In [2]:
a = np.array([0, 1, 2])
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[0 1 2]
int64


In [3]:
b = np.array([1, 1.5, 2])
print(b)
print(b.dtype)

c = np.array([1 + 2j, 3 + 4j, 5 + 6j])
print(c)
print(c.dtype)

d = np.array([True, False, True, False, False])
print(d)
print(d.dtype)

e = np.array(list("TechAcademy"))
print(e)
print(e.dtype)

[1.  1.5 2. ]
float64
[1.+2.j 3.+4.j 5.+6.j]
complex128
[ True False  True False False]
bool
['T' 'e' 'c' 'h' 'A' 'c' 'a' 'd' 'e' 'm' 'y']
<U1


In [4]:
f = np.array([100, 200, 300], dtype = np.int16)
print(f)
print(f.dtype)

[100 200 300]
int16


In [5]:
g = np.array([1.5, 2.5, 3.5])
print(g)
print(g.dtype)

[1.5 2.5 3.5]
float64


In [6]:
g = g.astype(np.int64)
print(g)
print(g.dtype)

[1 2 3]
int64


In [7]:
c = np.arange(2, 41, 2)
print(c)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [8]:
# 0以上10以下の数値を5分割
d = np.linspace(0, 10, 5)
print(d)

[ 0.   2.5  5.   7.5 10. ]


In [14]:
e = np.empty(2)
print(e)

[-5.73021895e-300  6.90276230e-310]


In [29]:
h = np.arange(1, 4)
i = np.arange(4, 7)
j = np.concatenate([h, i])
j

array([1, 2, 3, 4, 5, 6])

In [25]:
np.hstack([h,i])

array([1, 2, 3, 4, 5, 6])

In [31]:
j.tolist()

[1, 2, 3, 4, 5, 6]

In [38]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [48]:
a = np.arange(1, 21)
print(a)
print(a.shape)
a = a.reshape(4,5)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [47]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
a = np.arange(1, 101).reshape(10, 10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [51]:
print(a[1:3, 1:3])

[[12 13]
 [22 23]]


In [58]:
a = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
b = np.array([1, 1, 1])

# 第4引数で軸を決める
c = np.insert(a, 2, b, 0)
print(c)
c = np.insert(a, 2, b, 1)
print(c)

[[0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]]
[[0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]]


In [60]:
b = np.arange(1, 26).reshape(5, 5)
b = np.delete(b, 1, 0)
print(b)

b = np.delete(b, 1, 1)
print(b)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  3  4  5]
 [11 13 14 15]
 [16 18 19 20]
 [21 23 24 25]]


In [64]:
a = np.arange(1, 5).reshape(2, 2)
b = np.arange(5, 9).reshape(2, 2)
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [69]:
a = np.arange(1, 10).reshape(3, 3)
print(a)
a = np.fliplr(a)
a = np.flipud(a)
a

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [75]:
# 練習問題
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

b = np.arange(1, 10)
print(b)

b = b.reshape(9, 1)
print(b)

c = a * b
c

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [78]:
# 練習問題
d = np.zeros((9,9))
print(d)

d = d.astype(np.int8)

for i in range(9):
    for j in range(9):
        d[i, j] = (i + 1) * (j + 1)
print(d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
