In [1]:
class Person(object):
    def __init__(self, name):
        self.__nationality = 'Japan'
        self.name = name
    
    def say_hello(self):
        print(f'こんにちは。私の国籍は{self.__nationality}です。')
        self.__say_my_name()
    
    def __say_my_name(self):
        print(f'私の名前は{self.name}です。')

In [2]:
john = Person("John")
print(john.name)
john.say_hello()

John
こんにちは。私の国籍はJapanです。
私の名前はJohnです。


In [3]:
with open('sample.txt', 'r') as f:
    print(f.read())

はじめまして
こんにちは
こんばんは



In [4]:
import json

In [5]:
with open('sample.json', 'r') as f:
    data = json.load(f)
data

{'store_name': '神田店',
 'items': [{'item_id': 0, 'item_name': 'コーラ'},
  {'item_id': 1, 'item_name': 'マンガ'}]}

In [6]:
data['items'][0]['item_name']

'コーラ'

In [7]:
import os

In [8]:
for curDir, dirs, files in os.walk('.'):
    for file in files:
        print(f'{curDir}/{file}')

./sample.json
./practice2.ipynb
./practice3.ipynb
./practice1.ipynb
./sample.txt
./.ipynb_checkpoints/practice3-checkpoint.ipynb
./.ipynb_checkpoints/sample-checkpoint.json
./.ipynb_checkpoints/practice2-checkpoint.ipynb
./.ipynb_checkpoints/practice1-checkpoint.ipynb


In [9]:
lists = os.listdir('../..')
lists.sort()
lists

['.DS_Store',
 '.git',
 'calculation_memo',
 'front-dev-tutorial-master',
 'github-git-cheat-sheet.pdf',
 'linux_command.pdf',
 'port',
 'python_programming_demo_app-0.0.1',
 'python_training',
 'rails_apps',
 'ruby_shellscript']

In [10]:
os.path.abspath('./practice1.ipynb')

'/Users/satokota/Desktop/programming/python_training/knock/practice1.ipynb'

In [11]:
os.path.basename('./practice1.ipynb')

'practice1.ipynb'

In [12]:
os.path.exists('xyz/')

False

In [13]:
os.path.exists('./practice1.ipynb')

True

In [14]:
os.path.isdir('xyz/')

False

In [15]:
os.path.isdir('../knock')

True

In [16]:
os.path.isfile('practice1.ipynb')

True

In [17]:
for curDir, dirs, files in os.walk('.'):
    for file in files:
        print(os.path.join(curDir, file))

./sample.json
./practice2.ipynb
./practice3.ipynb
./practice1.ipynb
./sample.txt
./.ipynb_checkpoints/practice3-checkpoint.ipynb
./.ipynb_checkpoints/sample-checkpoint.json
./.ipynb_checkpoints/practice2-checkpoint.ipynb
./.ipynb_checkpoints/practice1-checkpoint.ipynb


In [18]:
os.mkdir('index')

In [19]:
os.rename('index', 'extreme')

In [20]:
os.rmdir('extreme')

In [21]:
os.environ['PATH']

'/Users/satokota/opt/anaconda3/bin:/Users/satokota/opt/anaconda3/condabin:/usr/local/opt/mysql@5.7/bin:/opt/homebrew/opt/openssl@1.1/bin:/opt/homebrew/opt/rbenv/shims:/opt/homebrew/opt/rbenv/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin'

In [22]:
# この方法はpythonスクリプトでないと機能しない
os.system('ls -l')

0

In [23]:
# jupyter上ではこのようにしないとUnixコマンドが使えない
print(os.popen('ls -l').read())

total 128
-rw-r--r--  1 satokota  staff  29404 Aug 19 10:38 practice1.ipynb
-rw-r--r--  1 satokota  staff   7932 Aug 19 10:38 practice2.ipynb
-rw-r--r--  1 satokota  staff  15308 Aug 19 11:18 practice3.ipynb
-rw-r--r--  1 satokota  staff    177 Aug 19 09:43 sample.json
-rw-r--r--  1 satokota  staff     51 Aug 19 09:33 sample.txt



In [24]:
!ls -l

total 128
-rw-r--r--  1 satokota  staff  29404 Aug 19 10:38 practice1.ipynb
-rw-r--r--  1 satokota  staff   7932 Aug 19 10:38 practice2.ipynb
-rw-r--r--  1 satokota  staff  15308 Aug 19 11:18 practice3.ipynb
-rw-r--r--  1 satokota  staff    177 Aug 19 09:43 sample.json
-rw-r--r--  1 satokota  staff     51 Aug 19 09:33 sample.txt


In [25]:
import numpy as np

In [26]:
a = np.array([1, 2, 3, 4])

In [27]:
a

array([1, 2, 3, 4])

In [28]:
a.shape

(4,)

In [29]:
b = np.array([[1, 2],
             [3, 4]])

In [30]:
b

array([[1, 2],
       [3, 4]])

In [31]:
b.shape

(2, 2)

In [32]:
np.zeros(8, )

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])