In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
a = np.array([[1, 5], [4, -2]])
a

array([[ 1,  5],
       [ 4, -2]])

In [4]:
b = np.array([[2, 1], [7, 6]])
b

array([[2, 1],
       [7, 6]])

In [5]:
a + b

array([[ 3,  6],
       [11,  4]])

In [6]:
np.dot(a, b)

array([[37, 31],
       [-6, -8]])

In [7]:
a = np.array([[1, 5, -2], [4, 0, -3], [-8, 2, 6]])
a

array([[ 1,  5, -2],
       [ 4,  0, -3],
       [-8,  2,  6]])

In [8]:
a.sum()

5

In [9]:
a.max()

6

In [10]:
a.min()

-8

In [11]:
np.average(a)

0.5555555555555556

In [12]:
np.median(a)

1.0

In [13]:
# 分散
np.var(a)

17.358024691358025

In [14]:
# 標準偏差
np.std(a)

4.166296279833928

In [15]:
a = np.array([[1, 5], [4, -2]])
a

array([[ 1,  5],
       [ 4, -2]])

In [16]:
# 行列式
np.linalg.det(a)

-22.000000000000004

In [17]:
# 逆行列
a_inv =np.linalg.inv(a)
a_inv

array([[ 0.09090909,  0.22727273],
       [ 0.18181818, -0.04545455]])

In [18]:
np.dot(a, a_inv)

array([[ 1.00000000e+00, -2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00]])

In [19]:
df = pd.read_csv('weather.csv')

In [20]:
df

年月日  平均気温(℃) 平均気温(℃).1 平均気温(℃).2  最高気温(℃) 最高気温(℃).1 最高気温(℃).2  \
0           NaN      NaN      品質情報      均質番号      NaN      品質情報      均質番号   
1    2019/12/14      9.3         8         1     15.9         8         1   
2    2019/12/15      7.8         8         1     11.1         8         1   
3    2019/12/16      6.9         8         1     12.5         8         1   
4    2019/12/17      8.2         8         1     10.3         8         1   
..          ...      ...       ...       ...      ...       ...       ...   
363  2020/12/10      8.7         8         1     11.1         8         1   
364  2020/12/11      9.2         8         1     13.8         8         1   
365  2020/12/12     10.4         8         1     14.0         8         1   
366  2020/12/13      8.6         8         1     14.4         8         1   
367  2020/12/14      7.8         8         1     12.2         8         1   

     最低気温(℃) 最低気温(℃).1 最低気温(℃).2  ...  平均雲量(10分比).2 平均蒸気圧(hPa) 平均蒸気圧(hPa).1  \
0        NaN      品質情報      均質番号  ...          均質番号        NaN         品質情報   
1        3.2         8         1  ...             1        NaN            0   
2        4.0         8         1  ...             1        NaN            0   
3        1.3         8         1  ...             1        NaN            0   
4        5.7         8         1  ...             1        NaN            0   
..       ...       ...       ...  ...           ...        ...          ...   
363      6.0         8         1  ...             1        NaN            0   
364      3.5         8         1  ...             1        NaN            0   
365      8.0         8         1  ...             1        NaN            0   
366      4.4         8         1  ...             1        NaN            0   
367      4.4         8         1  ...             1        NaN            0   

     平均蒸気圧(hPa).2 平均風速(m/s) 平均風速(m/s).1  平均風速(m/s).2 日照時間(時間) 日照時間(時間).1  \
0            均質番号       NaN        品質情報         均質番号      NaN       品質情報   
1               1       2.0           8            1      8.9          8   
2               1       2.3           8            1      6.3          8   
3               1       1.1           8            1      8.9          8   
4               1       1.1           8            1      0.2          8   
..            ...       ...         ...          ...      ...        ...   
363             1       1.4           8            1      0.0          8   
364             1       0.8           8            1      4.3          8   
365             1       1.4           8            1      1.4          8   
366             1       1.0           8            1      5.5          8   
367             1       1.9           8            1      4.4          8   

     日照時間(時間).2  
0          均質番号  
1             1  
2             1  
3             1  
4             1  
..          ...  
363           1  
364           1  
365           1  
366           1  
367           1  

[368 rows x 28 columns]

In [21]:
df.head(3)

年月日  平均気温(℃) 平均気温(℃).1 平均気温(℃).2  最高気温(℃) 最高気温(℃).1 最高気温(℃).2  \
0         NaN      NaN      品質情報      均質番号      NaN      品質情報      均質番号   
1  2019/12/14      9.3         8         1     15.9         8         1   
2  2019/12/15      7.8         8         1     11.1         8         1   

   最低気温(℃) 最低気温(℃).1 最低気温(℃).2  ...  平均雲量(10分比).2 平均蒸気圧(hPa) 平均蒸気圧(hPa).1  \
0      NaN      品質情報      均質番号  ...          均質番号        NaN         品質情報   
1      3.2         8         1  ...             1        NaN            0   
2      4.0         8         1  ...             1        NaN            0   

   平均蒸気圧(hPa).2 平均風速(m/s) 平均風速(m/s).1  平均風速(m/s).2 日照時間(時間) 日照時間(時間).1  \
0          均質番号       NaN        品質情報         均質番号      NaN       品質情報   
1             1       2.0           8            1      8.9          8   
2             1       2.3           8            1      6.3          8   

   日照時間(時間).2  
0        均質番号  
1           1  
2           1  

[3 rows x 28 columns]

In [22]:
df.tail(20)

年月日  平均気温(℃) 平均気温(℃).1 平均気温(℃).2  最高気温(℃) 最高気温(℃).1 最高気温(℃).2  \
348  2020/11/25     10.4         8         1     11.2         8         1   
349  2020/11/26     12.6         8         1     17.8         8         1   
350  2020/11/27     11.1         8         1     12.9         8         1   
351  2020/11/28     11.1         8         1     16.7         8         1   
352  2020/11/29      9.4         8         1     11.9         8         1   
353  2020/11/30      9.1         8         1     14.8         8         1   
354   2020/12/1      9.2         8         1     14.6         8         1   
355   2020/12/2      7.4         8         1      8.9         8         1   
356   2020/12/3      7.9         8         1     10.4         8         1   
357   2020/12/4      7.9         8         1     13.3         8         1   
358   2020/12/5      6.0         8         1      7.3         8         1   
359   2020/12/6      8.0         8         1     13.3         8         1   
360   2020/12/7      9.0         8         1     16.0         8         1   
361   2020/12/8     10.4         8         1     16.0         8         1   
362   2020/12/9      9.2         8         1     11.2         8         1   
363  2020/12/10      8.7         8         1     11.1         8         1   
364  2020/12/11      9.2         8         1     13.8         8         1   
365  2020/12/12     10.4         8         1     14.0         8         1   
366  2020/12/13      8.6         8         1     14.4         8         1   
367  2020/12/14      7.8         8         1     12.2         8         1   

     最低気温(℃) 最低気温(℃).1 最低気温(℃).2  ...  平均雲量(10分比).2 平均蒸気圧(hPa) 平均蒸気圧(hPa).1  \
348      9.4         8         1  ...             1        NaN            0   
349      9.5         8         1  ...             1        NaN            0   
350      9.5         8         1  ...             1        NaN            0   
351      7.2         8         1  ...             1        NaN            0   
352      5.7         8         1  ...             1        NaN            0   
353      4.5         8         1  ...             1        NaN            0   
354      3.9         8         1  ...             1        NaN            0   
355      6.2         8         1  ...             1        NaN            0   
356      6.5         8         1  ...             1        NaN            0   
357      3.8         8         1  ...             1        NaN            0   
358      4.3         8         1  ...             1        NaN            0   
359      4.5         8         1  ...             1        NaN            0   
360      4.2         8         1  ...             1        NaN            0   
361      4.6         8         1  ...             1        NaN            0   
362      8.3         8         1  ...             1        NaN            0   
363      6.0         8         1  ...             1        NaN            0   
364      3.5         8         1  ...             1        NaN            0   
365      8.0         8         1  ...             1        NaN            0   
366      4.4         8         1  ...             1        NaN            0   
367      4.4         8         1  ...             1        NaN            0   

     平均蒸気圧(hPa).2 平均風速(m/s) 平均風速(m/s).1  平均風速(m/s).2 日照時間(時間) 日照時間(時間).1  \
348             1       1.6           8            1      0.0          8   
349             1       1.0           8            1      6.8          8   
350             1       2.0           8            1      0.6          8   
351             1       2.2           8            1      9.0          8   
352             1       1.0           8            1      0.6          8   
353             1       1.3           8            1      6.6          8   
354             1       1.0           8            1      8.4          8   
355             1       1.6           8            1      0.0          8   
356             1       1.4           8           

In [23]:
df.columns

Index(['年月日', '平均気温(℃)', '平均気温(℃).1', '平均気温(℃).2', '最高気温(℃)', '最高気温(℃).1',
       '最高気温(℃).2', '最低気温(℃)', '最低気温(℃).1', '最低気温(℃).2', '降水量の合計(mm)',
       '降水量の合計(mm).1', '降水量の合計(mm).2', '最深積雪(cm)', '最深積雪(cm).1', '最深積雪(cm).2',
       '平均雲量(10分比)', '平均雲量(10分比).1', '平均雲量(10分比).2', '平均蒸気圧(hPa)',
       '平均蒸気圧(hPa).1', '平均蒸気圧(hPa).2', '平均風速(m/s)', '平均風速(m/s).1',
       '平均風速(m/s).2', '日照時間(時間)', '日照時間(時間).1', '日照時間(時間).2'],
      dtype='object')

In [24]:
# カラムを自由に選択, 1行目から読む
df = df[['年月日',
    '平均気温(℃)',
    '最高気温(℃)', 
    '最低気温(℃)',
    '降水量の合計(mm)',
    '最深積雪(cm)',
    '平均雲量(10分比)',
    '平均蒸気圧(hPa)',
    '平均風速(m/s)',
    '日照時間(時間)'
   ]][1:]

In [25]:
df

年月日  平均気温(℃)  最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)  平均雲量(10分比)  \
1    2019/12/14      9.3     15.9      3.2         0.0       NaN         NaN   
2    2019/12/15      7.8     11.1      4.0         0.0       NaN         NaN   
3    2019/12/16      6.9     12.5      1.3         0.0       NaN         NaN   
4    2019/12/17      8.2     10.3      5.7         2.0       NaN         NaN   
5    2019/12/18      9.9     15.0      4.8         0.0       NaN         NaN   
..          ...      ...      ...      ...         ...       ...         ...   
363  2020/12/10      8.7     11.1      6.0         0.5       NaN         NaN   
364  2020/12/11      9.2     13.8      3.5         0.0       NaN         NaN   
365  2020/12/12     10.4     14.0      8.0         0.0       NaN         NaN   
366  2020/12/13      8.6     14.4      4.4         0.0       NaN         NaN   
367  2020/12/14      7.8     12.2      4.4         0.0       NaN         NaN   

     平均蒸気圧(hPa)  平均風速(m/s)  日照時間(時間)  
1           NaN        2.0       8.9  
2           NaN        2.3       6.3  
3           NaN        1.1       8.9  
4           NaN        1.1       0.2  
5           NaN        1.2       4.3  
..          ...        ...       ...  
363         NaN        1.4       0.0  
364         NaN        0.8       4.3  
365         NaN        1.4       1.4  
366         NaN        1.0       5.5  
367         NaN        1.9       4.4  

[367 rows x 10 columns]

In [26]:
df.dtypes

年月日            object
平均気温(℃)       float64
最高気温(℃)       float64
最低気温(℃)       float64
降水量の合計(mm)    float64
最深積雪(cm)      float64
平均雲量(10分比)    float64
平均蒸気圧(hPa)    float64
平均風速(m/s)     float64
日照時間(時間)      float64
dtype: object

In [27]:
# 表サイズ
df.shape

(367, 10)

In [28]:
df.columns

Index(['年月日', '平均気温(℃)', '最高気温(℃)', '最低気温(℃)', '降水量の合計(mm)', '最深積雪(cm)',
       '平均雲量(10分比)', '平均蒸気圧(hPa)', '平均風速(m/s)', '日照時間(時間)'],
      dtype='object')

In [29]:
# 行名
df.index

RangeIndex(start=1, stop=368, step=1)

In [30]:
df.iloc[4:10, 2:6]

最高気温(℃)  最低気温(℃)  降水量の合計(mm)  最深積雪(cm)
5      15.0      4.8         0.0       NaN
6       9.7      7.9         1.0       NaN
7      15.8      5.7         0.0       NaN
8       8.4      6.5         0.0       NaN
9       9.8      4.2        21.0       NaN
10     12.1      3.6         9.5       NaN

In [31]:
df_people = pd.read_csv('people.csv')

In [32]:
df_people

age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
2   35  31    Suzuki       Japan
3   16  20      John     America
4   28  11       Kim       Korea

In [33]:
df_people[df_people['nationality'] == 'America']

age  id  name nationality
1   21  33  Mike     America
3   16  20  John     America

In [34]:
df_people.query('nationality == "America"')

age  id  name nationality
1   21  33  Mike     America
3   16  20  John     America

In [35]:
df_people[(df_people['age'] >= 20) & (df_people['age'] < 30)]

age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
4   28  11       Kim       Korea

In [36]:
df_people['nationality'].unique()

array(['Japan', 'America', 'Korea'], dtype=object)

In [37]:
# 重複除去
df_people.drop_duplicates(subset='nationality')

age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
4   28  11       Kim       Korea

In [38]:
# カラム名変更
df.columns

Index(['年月日', '平均気温(℃)', '最高気温(℃)', '最低気温(℃)', '降水量の合計(mm)', '最深積雪(cm)',
       '平均雲量(10分比)', '平均蒸気圧(hPa)', '平均風速(m/s)', '日照時間(時間)'],
      dtype='object')

In [39]:
df.columns = [
    '年月日',
    '平均気温',
    '最高気温',
    '最低気温',
    '降水量の合計',
    '最深積雪',
    '平均雲量',
    '平均蒸気圧',
    '平均風速',
    '日照時間'
]

In [40]:
df

年月日  平均気温  最高気温  最低気温  降水量の合計  最深積雪  平均雲量  平均蒸気圧  平均風速  日照時間
1    2019/12/14   9.3  15.9   3.2     0.0   NaN   NaN    NaN   2.0   8.9
2    2019/12/15   7.8  11.1   4.0     0.0   NaN   NaN    NaN   2.3   6.3
3    2019/12/16   6.9  12.5   1.3     0.0   NaN   NaN    NaN   1.1   8.9
4    2019/12/17   8.2  10.3   5.7     2.0   NaN   NaN    NaN   1.1   0.2
5    2019/12/18   9.9  15.0   4.8     0.0   NaN   NaN    NaN   1.2   4.3
..          ...   ...   ...   ...     ...   ...   ...    ...   ...   ...
363  2020/12/10   8.7  11.1   6.0     0.5   NaN   NaN    NaN   1.4   0.0
364  2020/12/11   9.2  13.8   3.5     0.0   NaN   NaN    NaN   0.8   4.3
365  2020/12/12  10.4  14.0   8.0     0.0   NaN   NaN    NaN   1.4   1.4
366  2020/12/13   8.6  14.4   4.4     0.0   NaN   NaN    NaN   1.0   5.5
367  2020/12/14   7.8  12.2   4.4     0.0   NaN   NaN    NaN   1.9   4.4

[367 rows x 10 columns]

In [41]:
# 最高気温高い順
df.sort_values('最高気温', ascending=False)

年月日  平均気温  最高気温  最低気温  降水量の合計  最深積雪  平均雲量  平均蒸気圧  平均風速  日照時間
248  2020/8/17  30.9  37.2  26.8     0.0   NaN   NaN    NaN   1.7   9.4
244  2020/8/13  30.4  37.1  26.9     0.5   NaN   NaN    NaN   1.6   8.5
246  2020/8/15  31.2  36.5  27.8     0.0   NaN   NaN    NaN   1.5   8.7
243  2020/8/12  30.3  35.9  27.6     0.0   NaN   NaN    NaN   1.8   7.2
252  2020/8/21  29.9  35.4  26.2     0.0   NaN   NaN    NaN   1.8  12.0
..         ...   ...   ...   ...     ...   ...   ...    ...   ...   ...
44   2020/1/26   4.6   7.0   1.7     5.5   NaN   NaN    NaN   0.9   0.0
45   2020/1/27   4.7   6.8   3.1     3.5   NaN   NaN    NaN   1.6   0.0
36   2020/1/18   3.8   6.2   0.9     7.5   NaN   NaN    NaN   2.5   0.0
40   2020/1/22   4.0   6.2   1.4     0.0   NaN   NaN    NaN   1.2   0.9
55    2020/2/6   2.3   5.5  -1.3     0.0   NaN   NaN    NaN   3.6   7.5

[367 rows x 10 columns]

In [42]:
# ダミーデータ処理
pd.get_dummies(df_people['nationality'])

America  Japan  Korea
0        0      1      0
1        1      0      0
2        0      1      0
3        1      0      0
4        0      0      1

In [43]:
pd.get_dummies(df_people, columns=['nationality'])

age  id      name  nationality_America  nationality_Japan  \
0   26  13  Imanishi                    0                  1   
1   21  33      Mike                    1                  0   
2   35  31    Suzuki                    0                  1   
3   16  20      John                    1                  0   
4   28  11       Kim                    0                  0   

   nationality_Korea  
0                  0  
1                  0  
2                  0  
3                  0  
4                  1

In [44]:
# 欠損値確認(NaNがTrueで返る)
print(df)
print(df.isnull())

            年月日  平均気温  最高気温  最低気温  降水量の合計  最深積雪  平均雲量  平均蒸気圧  平均風速  日照時間
1    2019/12/14   9.3  15.9   3.2     0.0   NaN   NaN    NaN   2.0   8.9
2    2019/12/15   7.8  11.1   4.0     0.0   NaN   NaN    NaN   2.3   6.3
3    2019/12/16   6.9  12.5   1.3     0.0   NaN   NaN    NaN   1.1   8.9
4    2019/12/17   8.2  10.3   5.7     2.0   NaN   NaN    NaN   1.1   0.2
5    2019/12/18   9.9  15.0   4.8     0.0   NaN   NaN    NaN   1.2   4.3
..          ...   ...   ...   ...     ...   ...   ...    ...   ...   ...
363  2020/12/10   8.7  11.1   6.0     0.5   NaN   NaN    NaN   1.4   0.0
364  2020/12/11   9.2  13.8   3.5     0.0   NaN   NaN    NaN   0.8   4.3
365  2020/12/12  10.4  14.0   8.0     0.0   NaN   NaN    NaN   1.4   1.4
366  2020/12/13   8.6  14.4   4.4     0.0   NaN   NaN    NaN   1.0   5.5
367  2020/12/14   7.8  12.2   4.4     0.0   NaN   NaN    NaN   1.9   4.4

[367 rows x 10 columns]
       年月日   平均気温   最高気温   最低気温  降水量の合計  最深積雪  平均雲量  平均蒸気圧   平均風速   日照時間
1    False  False  False  

In [45]:
# 欠損値０埋め
df.fillna(0).head()

年月日  平均気温  最高気温  最低気温  降水量の合計  最深積雪  平均雲量  平均蒸気圧  平均風速  日照時間
1  2019/12/14   9.3  15.9   3.2     0.0   0.0   0.0    0.0   2.0   8.9
2  2019/12/15   7.8  11.1   4.0     0.0   0.0   0.0    0.0   2.3   6.3
3  2019/12/16   6.9  12.5   1.3     0.0   0.0   0.0    0.0   1.1   8.9
4  2019/12/17   8.2  10.3   5.7     2.0   0.0   0.0    0.0   1.1   0.2
5  2019/12/18   9.9  15.0   4.8     0.0   0.0   0.0    0.0   1.2   4.3

In [46]:
# 欠損値の列削除
df.dropna(axis=1).head()

年月日  平均気温  最高気温  最低気温  降水量の合計  平均風速  日照時間
1  2019/12/14   9.3  15.9   3.2     0.0   2.0   8.9
2  2019/12/15   7.8  11.1   4.0     0.0   2.3   6.3
3  2019/12/16   6.9  12.5   1.3     0.0   1.1   8.9
4  2019/12/17   8.2  10.3   5.7     2.0   1.1   0.2
5  2019/12/18   9.9  15.0   4.8     0.0   1.2   4.3

In [47]:
df_iris = pd.read_csv('iris.csv')
df_iris

sepal-length  sepal-width  petal-length  petal-width            Class
0             5.1          3.5           1.4          0.2      Iris-setosa
1             4.9          3.0           1.4          0.2      Iris-setosa
2             4.7          3.2           1.3          0.2      Iris-setosa
3             4.6          3.1           1.5          0.2      Iris-setosa
4             5.0          3.6           1.4          0.2      Iris-setosa
..            ...          ...           ...          ...              ...
151          12.5          3.1           5.1          1.8   Iris-virginica
152          13.4          2.7           5.1          1.8   Iris-virginica
153          13.2          3.2           5.1          1.8  Iris-versicolor
154          15.2          2.3           5.1          1.8  Iris-versicolor
155          14.2          2.4           5.1          1.8  Iris-versicolor

[156 rows x 5 columns]

In [48]:
# ユニークな値の出現回数
df_iris['Class'].value_counts()

Iris-versicolor    53
Iris-virginica     53
Iris-setosa        50
Name: Class, dtype: int64

In [49]:
# 指定したカラム(グループごと)の平均値
df_iris.groupby('Class').mean()

sepal-length  sepal-width  petal-length  petal-width
Class                                                                
Iris-setosa          5.004255     3.434000      1.454000     0.244000
Iris-versicolor      6.403774     2.762264      4.307547     1.352830
Iris-virginica       6.937736     2.979245      5.526415     2.013208

In [50]:
df_iris.mean()

sepal-length    6.158824
sepal-width     3.051282
petal-length    3.807051
petal-width     1.221795
dtype: float64

In [51]:
df_iris.median()

sepal-length    5.80
sepal-width     3.00
petal-length    4.40
petal-width     1.35
dtype: float64

In [52]:
df_iris.std()

sepal-length    1.702457
sepal-width     0.437955
petal-length    1.753783
petal-width     0.757185
dtype: float64

In [53]:
df_iris.max()

sepal-length              15.2
sepal-width                4.4
petal-length               6.9
petal-width                2.5
Class           Iris-virginica
dtype: object

In [54]:
df_iris.min()

sepal-length            4.3
sepal-width             2.0
petal-length            1.0
petal-width             0.1
Class           Iris-setosa
dtype: object

In [55]:
df_iris['sepal-length'].mode()

0    5.0
dtype: float64